webtalk_init -webtalk_dir /home/hs/Desktop/git/benes_network_algorithm/rtl_code/16X16_network/16X16_module/16X16_module.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct  5 00:26:23 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3118627" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "db75e83e-a884-4c41-ae7f-1ad90a6941de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fb1c9653f2c24b97a95518348689cc46" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "57" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i9-12900K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4868.031 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3300 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126188_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1045673374 -regid "" -xml /home/hs/Desktop/git/benes_network_algorithm/rtl_code/16X16_network/16X16_module/16X16_module.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/hs/Desktop/git/benes_network_algorithm/rtl_code/16X16_network/16X16_module/16X16_module.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/hs/Desktop/git/benes_network_algorithm/rtl_code/16X16_network/16X16_module/16X16_module.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
